name: CI
on: [push]

jobs:
  makepkg:
    runs-on: ubuntu-22.04
    container:
      image: rnestler/archlinux-rust:add-a-builder-user
    steps:
      - run: pacman -Syu --noconfirm
      - run: pacman -S --noconfirm base-devel
      - uses: actions/checkout@v3
      - run: chown --recursive builder .
      - run: sudo --user=builder gpg --import keys/*.asc
      - run: sudo --user=builder makepkg --noconfirm -s --nobuild
